[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_SPOONACULAR_API_KEY = "${SPOONACULAR_API_KEY}"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
